// Package auth provides small, testable authentication primitives.
package auth

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"errors"
)

// Challenge contains a verifier and its RFC 7636 S256 challenge.
type Challenge struct {
	Verifier  string
	Challenge string
}

// NewPKCE generates a cryptographically random verifier (32 bytes) and challenge.
func NewPKCE() (Challenge, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return Challenge{}, err
	}
	v := base64.RawURLEncoding.EncodeToString(b)
	h := sha256.Sum256([]byte(v))
	return Challenge{Verifier: v, Challenge: base64.RawURLEncoding.EncodeToString(h[:])}, nil
}

// VerifyPKCE checks a verifier against an S256 challenge using constant-time comparison.
func VerifyPKCE(verifier, challenge string) error {
	if !validVerifier(verifier) || !validChallenge(challenge) {
		return errors.New("verifier and challenge are required")
	}
	h := sha256.Sum256([]byte(verifier))
	got := base64.RawURLEncoding.EncodeToString(h[:])
	if subtle.ConstantTimeCompare([]byte(got), []byte(challenge)) != 1 {
		return errors.New("pkce challenge mismatch")
	}
	return nil
}

// RFC 7636 permits a verifier of 43-128 unreserved ASCII characters. The
// server accepts only the URL-safe base64url form generated by NewPKCE; this
// avoids ambiguous encodings and rejects malformed input before hashing.
func validVerifier(verifier string) bool {
	if len(verifier) < 43 || len(verifier) > 128 {
		return false
	}
	for _, c := range verifier {
		if !((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' || c == '~') {
			return false
		}
	}
	return true
}
