CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pairing_codes(code TEXT PRIMARY KEY, expires_at TIMESTAMPTZ NOT NULL, device_name TEXT, device_type TEXT);
CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY, token_hash TEXT NOT NULL, name TEXT, type TEXT, public_key TEXT, created_at TIMESTAMPTZ NOT NULL, revoked BOOLEAN NOT NULL DEFAULT FALSE);
