export type MarketMode='single'|'portfolio'|'chain';
export type MarketSession={region:number;cargo:number;budget:number;reserve:number;minSec:number;maxJumps:number;plans:any[];selectedIndex:number|null;jobId?:string;jobState?:string;resultRevision:number};
export type MarketWorkspace={version:3;activeMode:MarketMode;byMode:Record<MarketMode,MarketSession>};
const defaults=():MarketSession=>({region:10000002,cargo:10000,budget:1_000_000_000,reserve:100_000_000,minSec:.5,maxJumps:15,plans:[],selectedIndex:null,resultRevision:0});
export const isRealMarketPlan=(p:any)=>{if(!p||typeof p!=='object')return false;const hasId=Number(p.typeId??p.TypeID)>0,items=p.items??p.Items,stops=p.stops??p.Stops;return hasId||(Array.isArray(items)&&items.length>0)||(Array.isArray(stops)&&stops.length>0)};
export const defaultMarketWorkspace=():MarketWorkspace=>({version:3,activeMode:'single',byMode:{single:defaults(),portfolio:defaults(),chain:defaults()}});
const sanitizeSession=(s:MarketSession):MarketSession=>{const plans=(Array.isArray(s.plans)?s.plans:[]).filter(isRealMarketPlan);return {...s,plans,selectedIndex:plans.length?Math.min(Number(s.selectedIndex)||0,plans.length-1):null}}
export function loadMarketWorkspace(storage:Pick<Storage,'getItem'>=localStorage):MarketWorkspace{const base=defaultMarketWorkspace();try{const raw=storage.getItem('alice.market.workspace.v3');if(raw){const v=JSON.parse(raw);if(v?.version===3&&v?.byMode)return {version:3,activeMode:['single','portfolio','chain'].includes(v.activeMode)?v.activeMode:'single',byMode:{single:sanitizeSession({...base.byMode.single,...v.byMode.single}),portfolio:sanitizeSession({...base.byMode.portfolio,...v.byMode.portfolio}),chain:sanitizeSession({...base.byMode.chain,...v.byMode.chain})}}}const old=storage.getItem('alice.market.plan.v2');if(old){const v=JSON.parse(old),m:MarketMode=v.mode==='portfolio'||v.mode==='chain'?v.mode:'single';base.activeMode=m;base.byMode[m]={...base.byMode[m],plans:Array.isArray(v.plans)?v.plans:[],selectedIndex:Number.isInteger(v.selectedIndex)?v.selectedIndex:null}}const region=Number(storage.getItem('alice.market.region'));const cargo=Number(storage.getItem('alice.market.cargo'));for(const m of ['single','portfolio','chain'] as MarketMode[]){if(region>0)base.byMode[m].region=region;if(cargo>0)base.byMode[m].cargo=cargo}}catch{}return base}
export function saveMarketWorkspace(workspace:MarketWorkspace,storage:Pick<Storage,'setItem'>=localStorage){storage.setItem('alice.market.workspace.v3',JSON.stringify(workspace))}
export function replaceModeSession(workspace:MarketWorkspace,mode:MarketMode,session:MarketSession):MarketWorkspace{return {...workspace,byMode:{...workspace.byMode,[mode]:session}}}
export function latestRevisionResults(items:any[]):{revision:number;plans:any[]}{if(!items.length)return {revision:0,plans:[]};const revision=Math.max(...items.map(x=>Number(x?.revision??x?.Revision??0)));return {revision,plans:items.filter(x=>Number(x?.revision??x?.Revision??0)===revision).sort((a,b)=>Number(a?.rank??a?.Rank??0)-Number(b?.rank??b?.Rank??0)).map(x=>{const p=x?.payload??x?.Payload??x,s=Number(x?.score??x?.Score);return Number.isFinite(s)&&p&&typeof p==='object'?{...p,score:s}:p})}}
export function applyJobResults(workspace:MarketWorkspace,mode:MarketMode,jobId:string,plans:any[],revision:number):MarketWorkspace{const current=workspace.byMode[mode];if(current.jobId!==jobId)return workspace;const valid=plans.filter(isRealMarketPlan);return replaceModeSession(workspace,mode,{...current,plans:valid,selectedIndex:valid.length?Math.min(current.selectedIndex??0,valid.length-1):null,resultRevision:revision})}
export function applyJobState(workspace:MarketWorkspace,mode:MarketMode,jobId:string,state:string,revision:number):MarketWorkspace{const current=workspace.byMode[mode];if(current.jobId!==jobId)return workspace;return replaceModeSession(workspace,mode,{...current,jobState:state,resultRevision:revision})}
