import 'package:flutter/material.dart';
import 'api/api_client.dart';
import 'models/protocol.dart';

void main() => runApp(const EveAssistantApp());
class EveAssistantApp extends StatelessWidget { const EveAssistantApp({super.key}); @override Widget build(BuildContext c) => MaterialApp(title: 'EVE 助手', home: const HomePage()); }
class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState() => _HomePageState(); }
class _HomePageState extends State<HomePage> {
  final api = RelayApiClient(baseUrl: 'https://alice.guyufl.us.ci');
  int tab = 0; List<AlertEvent> alerts = [];
  Future<void> refresh() async { try { final a = await api.fetchAlerts(); if (mounted) setState(() => alerts = a); } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('刷新失败，请检查配对状态'))); } }
  @override Widget build(BuildContext c) => Scaffold(appBar: AppBar(title: const Text('EVE 助手')), body: tab == 0 ? const Center(child: Text('演示版：无需完整 SSO')) : tab == 1 ? PairingPanel(api: api, onPaired: refresh) : AlertList(alerts: alerts, api: api, onRefresh: refresh), bottomNavigationBar: NavigationBar(selectedIndex: tab, onDestinationSelected: (i) => setState(() => tab = i), destinations: const [NavigationDestination(icon: Icon(Icons.login), label: '登录'), NavigationDestination(icon: Icon(Icons.devices), label: '配对'), NavigationDestination(icon: Icon(Icons.notifications), label: '告警')]));
}
class PairingPanel extends StatefulWidget { final ApiClient api; final VoidCallback onPaired; const PairingPanel({required this.api, required this.onPaired, super.key}); @override State<PairingPanel> createState() => _PairingState(); }
class _PairingState extends State<PairingPanel> { final code = TextEditingController(); bool busy = false; Future<void> pair() async { if (code.text.trim().isEmpty) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('请输入配对码'))); return; } setState(() => busy = true); try { await widget.api.confirmPairing(code.text.trim()); if (mounted) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('配对成功'))); widget.onPaired(); } } catch (_) { if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('配对失败，请检查配对码'))); } finally { if (mounted) setState(() => busy = false); } } @override Widget build(BuildContext c) => Padding(padding: const EdgeInsets.all(24), child: Column(children: [TextField(controller: code, decoration: const InputDecoration(labelText: '桌面端配对码')), const SizedBox(height: 16), FilledButton(onPressed: busy ? null : pair, child: Text(busy ? '配对中…' : '确认配对'))])); }
class AlertList extends StatelessWidget { final List<AlertEvent> alerts; final ApiClient api; final Future<void> Function() onRefresh; const AlertList({required this.alerts, required this.api, required this.onRefresh, super.key}); @override Widget build(BuildContext c) { final children = <Widget>[]; if (alerts.isEmpty) { children.addAll([const SizedBox(height: 200), const Center(child: Text('暂无告警'))]); } else { children.addAll(alerts.map((a) => ListTile(title: Text(a.title), subtitle: Text(a.summary), trailing: TextButton(onPressed: () async { try { await api.acknowledgeAlert(a.id); await onRefresh(); } catch (_) { if (c.mounted) ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content: Text('确认失败'))); } }, child: const Text('确认'))))); } return RefreshIndicator(onRefresh: onRefresh, child: ListView(children: children)); } }
