// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRelayHealth() {
  return window['go']['main']['App']['CheckRelayHealth']();
}

export function GeneratePairingCode() {
  return window['go']['main']['App']['GeneratePairingCode']();
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function PublishTestAlert() {
  return window['go']['main']['App']['PublishTestAlert']();
}

export function RelayURL() {
  return window['go']['main']['App']['RelayURL']();
}

export function SetRelayURL(arg1) {
  return window['go']['main']['App']['SetRelayURL'](arg1);
}
