// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRelayHealth():Promise<void>;

export function GeneratePairingCode():Promise<string>;

export function Health():Promise<string>;

export function PublishTestAlert():Promise<void>;

export function RelayURL():Promise<string>;

export function SetRelayURL(arg1:string):Promise<void>;
