// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckRealtimeEvent(arg1, arg2) {
  return window['go']['main']['App']['AckRealtimeEvent'](arg1, arg2);
}

export function AuthorizeDevice(arg1, arg2) {
  return window['go']['main']['App']['AuthorizeDevice'](arg1, arg2);
}

export function BeginOAuthLogin(arg1) {
  return window['go']['main']['App']['BeginOAuthLogin'](arg1);
}

export function CancelAgentRun(arg1, arg2) {
  return window['go']['main']['App']['CancelAgentRun'](arg1, arg2);
}

export function CheckRelayHealth() {
  return window['go']['main']['App']['CheckRelayHealth']();
}

export function ClearPairing() {
  return window['go']['main']['App']['ClearPairing']();
}

export function CloseLocalAgentSession(arg1) {
  return window['go']['main']['App']['CloseLocalAgentSession'](arg1);
}

export function CompleteOAuthLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteOAuthLogin'](arg1, arg2, arg3);
}

export function ConfirmPairing(arg1) {
  return window['go']['main']['App']['ConfirmPairing'](arg1);
}

export function FetchAlerts(arg1, arg2) {
  return window['go']['main']['App']['FetchAlerts'](arg1, arg2);
}

export function FetchConversationMessages(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchConversationMessages'](arg1, arg2, arg3);
}

export function FetchConversations() {
  return window['go']['main']['App']['FetchConversations']();
}

export function FetchOutbox(arg1, arg2) {
  return window['go']['main']['App']['FetchOutbox'](arg1, arg2);
}

export function FetchRealtimeSnapshot() {
  return window['go']['main']['App']['FetchRealtimeSnapshot']();
}

export function GeneratePairingCode() {
  return window['go']['main']['App']['GeneratePairingCode']();
}

export function GetAgentRun(arg1, arg2) {
  return window['go']['main']['App']['GetAgentRun'](arg1, arg2);
}

export function HandleLocalAgentRequest(arg1) {
  return window['go']['main']['App']['HandleLocalAgentRequest'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListAgentRunEvents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListAgentRunEvents'](arg1, arg2, arg3, arg4);
}

export function NextRealtimeEvent() {
  return window['go']['main']['App']['NextRealtimeEvent']();
}

export function OpenLocalAgentSession() {
  return window['go']['main']['App']['OpenLocalAgentSession']();
}

export function PairingState() {
  return window['go']['main']['App']['PairingState']();
}

export function ParseIntel(arg1) {
  return window['go']['main']['App']['ParseIntel'](arg1);
}

export function PollOAuthLogin() {
  return window['go']['main']['App']['PollOAuthLogin']();
}

export function PublishTestAlert() {
  return window['go']['main']['App']['PublishTestAlert']();
}

export function QueryESI(arg1) {
  return window['go']['main']['App']['QueryESI'](arg1);
}

export function QuerySDE(arg1, arg2) {
  return window['go']['main']['App']['QuerySDE'](arg1, arg2);
}

export function RealtimeStatus() {
  return window['go']['main']['App']['RealtimeStatus']();
}

export function RefreshOAuthToken() {
  return window['go']['main']['App']['RefreshOAuthToken']();
}

export function ReindexSDE() {
  return window['go']['main']['App']['ReindexSDE']();
}

export function RelayURL() {
  return window['go']['main']['App']['RelayURL']();
}

export function SDEDirectory() {
  return window['go']['main']['App']['SDEDirectory']();
}

export function SDEStatus() {
  return window['go']['main']['App']['SDEStatus']();
}

export function SendAgentMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendAgentMessage'](arg1, arg2, arg3, arg4);
}

export function SetRelayURL(arg1) {
  return window['go']['main']['App']['SetRelayURL'](arg1);
}

export function SetSDEDirectory(arg1) {
  return window['go']['main']['App']['SetSDEDirectory'](arg1);
}

export function StartAgentRun(arg1, arg2) {
  return window['go']['main']['App']['StartAgentRun'](arg1, arg2);
}

export function StartRealtime(arg1, arg2) {
  return window['go']['main']['App']['StartRealtime'](arg1, arg2);
}

export function StopRealtime() {
  return window['go']['main']['App']['StopRealtime']();
}
