// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {storage} from '../models';
import {protocol} from '../models';
import {eve} from '../models';

export function AckRealtimeEvent(arg1:app.RealtimeEvent,arg2:string):Promise<void>;

export function AuthorizeDevice(arg1:string,arg2:string):Promise<Record<string, any>>;

export function BeginOAuthLogin(arg1:string):Promise<Record<string, any>>;

export function CancelAgentRun(arg1:string,arg2:string):Promise<app.AgentRun>;

export function CheckRelayHealth():Promise<void>;

export function ClearPairing():Promise<void>;

export function CloseLocalAgentSession(arg1:string):Promise<void>;

export function CompleteOAuthLogin(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ConfirmPairing(arg1:string):Promise<storage.PairingState>;

export function FetchAlerts(arg1:number,arg2:number):Promise<app.DataPage_eve_assistant_desktop_app_internal_app_AlertItem_>;

export function FetchConversationMessages(arg1:string,arg2:number,arg3:number):Promise<app.ConversationMessagePage>;

export function FetchConversations():Promise<Array<app.AgentConversation>>;

export function FetchOutbox(arg1:number,arg2:number):Promise<app.DataPage_eve_assistant_desktop_app_internal_app_OutboxItem_>;

export function FetchRealtimeSnapshot():Promise<string>;

export function GeneratePairingCode():Promise<string>;

export function GetAgentRun(arg1:string,arg2:string):Promise<app.AgentRun>;

export function HandleLocalAgentRequest(arg1:string):Promise<string>;

export function Health():Promise<string>;

export function ListAgentRunEvents(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<app.AgentRunEvent>>;

export function NextRealtimeEvent():Promise<app.RealtimeEvent|boolean>;

export function OpenLocalAgentSession():Promise<Record<string, any>>;

export function PairingState():Promise<storage.PairingState>;

export function ParseIntel(arg1:string):Promise<Array<protocol.IntelFinding>>;

export function PublishTestAlert():Promise<void>;

export function QueryESI(arg1:string):Promise<eve.ESIResponse>;

export function QuerySDE(arg1:string,arg2:number):Promise<Array<eve.SDEEntry>>;

export function RealtimeStatus():Promise<app.RealtimeStatus>;

export function RefreshOAuthToken():Promise<void>;

export function ReindexSDE():Promise<eve.SDEStatus>;

export function RelayURL():Promise<string>;

export function SDEDirectory():Promise<string>;

export function SDEStatus():Promise<eve.SDEStatus>;

export function SendAgentMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function SetRelayURL(arg1:string):Promise<void>;

export function SetSDEDirectory(arg1:string):Promise<void>;

export function StartAgentRun(arg1:string,arg2:string):Promise<app.AgentRun>;

export function StartRealtime(arg1:string,arg2:string):Promise<void>;

export function StopRealtime():Promise<void>;
