// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {storage} from '../models';
import {evesde} from '../models';
import {protocol} from '../models';
import {eve} from '../models';

export function AckRealtimeEvent(arg1:app.RealtimeEvent,arg2:string):Promise<void>;

export function AuthorizeDevice(arg1:string,arg2:string):Promise<Record<string, any>>;

export function BeginOAuthLogin(arg1:string):Promise<Record<string, any>>;

export function CancelAgentRun(arg1:string,arg2:string):Promise<app.AgentRun>;

export function ChainEVETradePlans(arg1:app.TradeChainRequest):Promise<Array<Record<string, any>>>;

export function ChatLogStatus():Promise<app.ChatLogStatus>;

export function CheckRelayHealth():Promise<void>;

export function ClearPairing():Promise<void>;

export function CloseLocalAgentSession(arg1:string):Promise<void>;

export function CollectEVETradeRegion(arg1:number):Promise<app.TradeRegionStatus>;

export function CompleteOAuthLogin(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ComposeEVETradePlan(arg1:app.TradePackRequest):Promise<Array<Record<string, any>>>;

export function ConfirmPairing(arg1:string):Promise<storage.PairingState>;

export function FetchAlerts(arg1:number,arg2:number):Promise<app.DataPage_eve_assistant_desktop_app_internal_app_AlertItem_>;

export function FetchConversationMessages(arg1:string,arg2:number,arg3:number):Promise<app.ConversationMessagePage>;

export function FetchConversations():Promise<Array<app.AgentConversation>>;

export function FetchEVEAccountCharacters():Promise<Array<app.CharacterSnapshot>>;

export function FetchEVEAlliance(arg1:number):Promise<app.EVEAlliance>;

export function FetchEVECharacterSnapshot(arg1:number,arg2:string):Promise<app.CharacterSnapshot>;

export function FetchEVECharacterSnapshots(arg1:number):Promise<Array<app.CharacterSnapshot>>;

export function FetchEVECharacterTradeContext(arg1:number,arg2:number,arg3:number):Promise<app.CharacterTradeContext>;

export function FetchEVEContractBids(arg1:number,arg2:number):Promise<Array<Record<string, any>>>;

export function FetchEVEContractItems(arg1:number,arg2:number):Promise<Array<Record<string, any>>>;

export function FetchEVECorporation(arg1:number):Promise<app.EVECorporation>;

export function FetchEVEHubComparison(arg1:number):Promise<Array<app.EVEHubQuote>>;

export function FetchEVEKillmailDetail(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function FetchEVEMailBody(arg1:number,arg2:number):Promise<Record<string, any>>;

export function FetchEVEMarketHistory(arg1:number,arg2:number):Promise<Array<app.EVEMarketHistory>>;

export function FetchEVEMarketOrders(arg1:number,arg2:string,arg3:number):Promise<Array<app.EVEMarketOrder>>;

export function FetchEVEMarketPrices():Promise<Array<app.EVEMarketPrice>>;

export function FetchEVESecureTradeRoute(arg1:number,arg2:number,arg3:number,arg4:number):Promise<app.TradeRouteResult>;

export function FetchEVESecureTradeRoutes(arg1:Array<app.TradeRouteQuery>):Promise<Array<app.TradeRouteResult>>;

export function FetchEVEStatus():Promise<app.EVEStatus>;

export function FetchEVESyncStatus():Promise<Array<app.EVESyncJob>>;

export function FetchEVETradeHubs():Promise<Array<app.EVETradeHub>>;

export function FetchEVETradePlans(arg1:app.EVETradePlanRequest):Promise<Array<Record<string, any>>>;

export function FetchEVETradeRegionCollection(arg1:number):Promise<app.TradeRegionStatus>;

export function FetchEVETradeRoute(arg1:number,arg2:number,arg3:string,arg4:number):Promise<evesde.RouteResult>;

export function FetchEVEUniverseNames(arg1:Array<number>):Promise<Array<app.EVEUniverseName>>;

export function FetchEVEUniverseStation(arg1:number):Promise<app.EVEStation>;

export function FetchEVEUniverseSystem(arg1:number):Promise<app.EVESolarSystem>;

export function FetchEVEUniverseType(arg1:number):Promise<app.EVEItemType>;

export function FetchOutbox(arg1:number,arg2:number):Promise<app.DataPage_eve_assistant_desktop_app_internal_app_OutboxItem_>;

export function FetchRealtimeSnapshot():Promise<string>;

export function GameLogStatus():Promise<app.GameLogStatus>;

export function GeneratePairingCode():Promise<string>;

export function GetAgentRun(arg1:string,arg2:string):Promise<app.AgentRun>;

export function HandleLocalAgentRequest(arg1:string):Promise<string>;

export function Health():Promise<string>;

export function ListAgentRunEvents(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<app.AgentRunEvent>>;

export function NextRealtimeEvent():Promise<app.RealtimeEvent|boolean>;

export function OpenLocalAgentSession():Promise<Record<string, any>>;

export function PairingState():Promise<storage.PairingState>;

export function ParseIntel(arg1:string):Promise<Array<protocol.IntelFinding>>;

export function PollOAuthLogin():Promise<Record<string, any>>;

export function PublishChatIntel(arg1:string):Promise<void>;

export function PublishTestAlert():Promise<void>;

export function QueryESI(arg1:string):Promise<eve.ESIResponse>;

export function QuerySDE(arg1:string,arg2:number):Promise<Array<eve.SDEEntry>>;

export function RealtimeStatus():Promise<app.RealtimeStatus>;

export function RecentChatIntel():Promise<Array<app.ChatIntelEvent>>;

export function RecentGameEvents():Promise<Array<app.GameLogEvent>>;

export function RefreshOAuthToken():Promise<void>;

export function ReindexSDE():Promise<eve.SDEStatus>;

export function RelayURL():Promise<string>;

export function RestartChatLogWatcher():Promise<void>;

export function SDEDirectory():Promise<string>;

export function SDELocationNames(arg1:Array<number>):Promise<Record<number, string>>;

export function SDEStatus():Promise<eve.SDEStatus>;

export function SDETypeNames(arg1:Array<number>):Promise<Record<number, string>>;

export function SearchEVETradeCandidates(arg1:app.TradeCandidateSearch):Promise<app.TradeCandidatePage>;

export function SendAgentMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function SetChatLogsDirectory(arg1:string):Promise<void>;

export function SetRelayURL(arg1:string):Promise<void>;

export function SetSDEDirectory(arg1:string):Promise<void>;

export function StartAgentRun(arg1:string,arg2:string):Promise<app.AgentRun>;

export function StartRealtime(arg1:string,arg2:string):Promise<void>;

export function StartupError():Promise<string>;

export function StopRealtime():Promise<void>;

export function StoredLocalEvents(arg1:string,arg2:number):Promise<Array<storage.NormalizedLocalEvent>>;
